spring:
  application:
    name: mybatis-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: dev
    password: abc123
    driver-class-name: org.postgresql.Driver

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zhaomsdemo.research.mybatisdemo.model
